namespace Microsoft.Toolkit.Win32.UI.XamlHost
{
    [default_interface]
    unsealed runtimeclass DesktopWindow : Windows.UI.Xaml.DependencyObject, Windows.Foundation.IClosable
    {
        DesktopWindow();

        Windows.UI.Xaml.UIElement Content{ get; set; };

        String Title{ get; set; };

        void Show();

        void Close();
    }
}